---
env: dev
image: ""
serviceAccount: null

autoscaling:
  enabled: false
  replicas:
    min: 2
    max: 10
  averageUtilization:
    cpu: 80
    memory: 80

monitoring:
  enabled: false

externalSecret:
  enabled: true

deployment:
  containers:
    default:
      resources:
        requests:
          cpu: 200m
        limits:
          memory: 700Mi

      # extra environment variables from ConfigMaps like
      # envConfig;
      #   <ENV_VAR_NAME>: <keyOfValueInConfigMap>
      configMapEnv: {}

      # extra environment variables from Secrets like
      # envSecret;
      #   <ENV_VAR_NAME>: <keyOfValueInSecret>
      secretEnv: {}

      # extra static environment variables like
      # envVars;
      #   <ENV_VAR_NAME>: <envVarValue>
      staticEnv: {}

      ports:
        http: 3000

      startupProbe:
        failureThreshold: 30
        period: 3
        type: httpGet
        port: http
        path: /

      livenessProbe:
        period: 10
        type: httpGet
        port: http
        path: /

federationSchemaPublish:
  command: null

  # extra environment variables from ConfigMaps like
  # envConfig;
  #   <ENV_VAR_NAME>: <keyOfValueInConfigMap>
  configMapEnv: {}

  # extra environment variables from Secrets like
  # envSecret;
  #   <ENV_VAR_NAME>: <keyOfValueInSecret>
  secretEnv: {}

  # extra static environment variables like
  # envVars;
  #   <ENV_VAR_NAME>: <envVarValue>
  staticEnv: {}

service:
  enabled: true
  type: NodePort

ingress:
  enabled: false
  pathPrefix: null
  hostnames: []
